using AutoMapper;
using FlowerSellingWebsite.Models.DTOs;
using FlowerSellingWebsite.Models.DTOs.Flower;
using FlowerSellingWebsite.Models.Entities;
using FlowerSellingWebsite.Services.Interfaces;
using FlowerSellingWebsite.Repositories.Interfaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using FlowerSelling.Data.FlowerSellingWebsite.Data;

namespace FlowerSellingWebsite.Services.Implementations
{
    public class FlowerService : IFlowerService
    {
        private readonly IBaseRepository<Flowers> _flowerRepo;
        private readonly IBaseRepository<ProductFlowers> _productFlowerRepo;
        private readonly IBaseRepository<FlowerPricing> _flowerPricingRepo;
        private readonly IBaseRepository<FlowerImages> _flowerImage;
        private readonly IBaseRepository<SupplierListings> _supplierListingRepository;
        private readonly FlowerSellingDbContext _context;
        
        private readonly IMapper _mapper;

        public FlowerService(IBaseRepository<Flowers> flowerRepo, IBaseRepository<FlowerPricing> flowerPricingRepo, IBaseRepository<FlowerImages> flowerImage, IMapper mapper, IBaseRepository<SupplierListings> supplierListingRepository, IBaseRepository<ProductFlowers> productFlowerRepo, FlowerSellingDbContext context)
        {
            _flowerRepo = flowerRepo;
            _mapper = mapper;
            _supplierListingRepository = supplierListingRepository;
            _productFlowerRepo = productFlowerRepo;
            _flowerPricingRepo = flowerPricingRepo;
            _flowerImage = flowerImage;
            _context = context;
        }

        public async Task<bool> CreateFlowerWithSupplier(CreateSupplierListingRequest request, int supplierId)
        {
            try
            {
                var flower = await _flowerRepo.AsQueryable().FirstOrDefaultAsync(x => x.Id == request.ProductFlowers.FlowerId);

                var supplierListing = new SupplierListings
                {
                    SupplierId = supplierId,
                    FlowerId = flower.Id,
                    AvailableQuantity = request.ProductFlowers.Quantity,
                    UnitPrice = request.FlowerPriceRequests.Price,
                    ShelfLifeDays = request.ShelfLifeDays,
                    MinOrderQty = request.MinOrderQty,
                    Status = "pending"
                };

                var historyPrice = new FlowerPricing
                {
                    FlowerId = flower.Id,
                    Price = request.FlowerPriceRequests.Price,
                    Currency = "VND",
                    EffectiveDate = request.FlowerPriceRequests.EffectiveDate,
                    ExpiryDate = request.FlowerPriceRequests.ExpiryDate,
                    PriceType = "type",
                    IsActive = true
                };

                await _supplierListingRepository.createAsync(supplierListing);
                await _flowerPricingRepo.createAsync(historyPrice);

                return true;
            } catch (Exception ex)
            {
                return false;
            }
        }

        public async Task<bool> CreateFlowerAsync(CreateFlowerWithSupplierRequest request, int supplerId)
        {
            try
            {
                var flowerType = await _context.FlowerTypes
                    .Where(x => x.Id == request.FlowerTypeId && !x.IsDeleted)
                    .Select(x => x.TypeName)
                    .FirstOrDefaultAsync();

                var flowerCategory = await _context.FlowerCategories
                    .Where(x => x.Id == request.FlowerCategoryId && !x.IsDeleted)
                    .Select(x => x.CategoryName)
                    .FirstOrDefaultAsync();

                var flowerColor = await _context.FlowerColors
                    .Where(x => x.Id == request.FlowerColorId && !x.IsDeleted)
                    .Select(x => x.ColorName)
                    .FirstOrDefaultAsync();

                var autoGeneratedName = $"{flowerType} {flowerCategory} {flowerColor} {request.Size}".Trim();

                // if name already exists
                var isExist = await _flowerRepo.AsQueryable().AnyAsync(x => x.Name == autoGeneratedName);

                if (isExist) 
                {
                    // If exists, add a number suffix
                    int counter = 1;
                    while (await _flowerRepo.AsQueryable().AnyAsync(x => x.Name == $"{autoGeneratedName} {counter}"))
                    {
                        counter++;
                    }
                    autoGeneratedName = $"{autoGeneratedName} {counter}";
                }

                var newFlower = new Flowers
                {
                    Name = autoGeneratedName,
                    Description = request.Description,
                    FlowerCategoryId = request.FlowerCategoryId,
                    FlowerTypeId = request.FlowerTypeId,
                    FlowerColorId = request.FlowerColorId,
                    Size = request.Size,
                    ShelfLifeDays = 7 // Default shelf life
                };

                var rsflower = await _flowerRepo.createAsync(newFlower);

                var newImage = new FlowerImages
                {
                    FlowerId = rsflower.Id,
                    ImageUrl = request.FlowerImageRequests.ImageUrl,
                    ImageType = request.FlowerImageRequests.ImageType,
                    IsPrimary = request.FlowerImageRequests.IsPrimary,
                    DisplayOrder = request.FlowerImageRequests.DisplayOrder,
                    IsActive = true
                };

                await _flowerImage.createAsync(newImage);

                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        public async Task<IEnumerable<FlowerCategoryResponse>> GetFlowerCategoriesAsync()
        {
            var categories = await _context.FlowerCategories
                .Where(x => !x.IsDeleted)
                .Select(x => new FlowerCategoryResponse
                {
                    Id = x.Id,
                    CategoryName = x.CategoryName,
                    Description = x.Description
                })
                .ToListAsync();

            return categories;
        }

        public async Task<IEnumerable<FlowerTypeResponse>> GetFlowerTypesAsync()
        {
            var types = await _context.FlowerTypes
                .Where(x => !x.IsDeleted)
                .Select(x => new FlowerTypeResponse
                {
                    Id = x.Id,
                    TypeName = x.TypeName,
                    Description = x.Description
                })
                .ToListAsync();

            return types;
        }

        public async Task<IEnumerable<FlowerColorResponse>> GetFlowerColorsAsync()
        {
            var colors = await _context.FlowerColors
                .Where(x => !x.IsDeleted)
                .Select(x => new FlowerColorResponse
                {
                    Id = x.Id,
                    ColorName = x.ColorName,
                    Description = x.Description
                })
                .ToListAsync();

            return colors;
        }

        public async Task<IEnumerable<FlowerDTO>> GetAllFlowersAsync()
        {
            var flowers = await _context.Flowers
                .Where(x => !x.IsDeleted)
                .Select(x => new FlowerDTO
                {
                    Id = x.Id,
                    Name = x.Name,
                    Description = x.Description,
                    Size = x.Size,
                    ShelfLifeDays = x.ShelfLifeDays,
                    FlowerCategoryId = x.FlowerCategoryId,
                    CategoryName = x.FlowerCategory != null ? x.FlowerCategory.CategoryName : null,
                    FlowerTypeId = x.FlowerTypeId,
                    TypeName = x.FlowerType != null ? x.FlowerType.TypeName : null,
                    FlowerColorId = x.FlowerColorId,
                    ColorName = x.FlowerColor != null ? x.FlowerColor.ColorName : null
                })
                .ToListAsync();

            return flowers;
        }

        public async Task<PagedResult<FlowerResponse>> GetListFlowerAsync(UrlQueryParams queryParams, int? supplierId = null)
        {
            IQueryable<Flowers> flowerQuery = _flowerRepo.AsQueryable()
                .Include(x => x.FlowerCategory)
                .Include(x => x.FlowerType)
                .Include(x => x.FlowerColor);

            if (supplierId.HasValue)
            {
                //flowerQuery = flowerQuery.Where(x => x.SupplierId == supplierId.Value);
            }

            if (!string.IsNullOrEmpty(queryParams.SearchBy) && !string.IsNullOrEmpty(queryParams.SearchValue))
            {
                flowerQuery = queryParams.SearchBy.ToLower() switch
                {
                    "category" => flowerQuery.Where(x => x.FlowerCategory.CategoryName.Contains(queryParams.SearchValue)),
                    "size" => flowerQuery.Where(x => x.Size.Contains(queryParams.SearchValue)),
                    "type" => flowerQuery.Where(x => x.FlowerType.TypeName.Contains(queryParams.SearchValue)),
                    "color" => flowerQuery.Where(x => x.FlowerColor.ColorName.Contains(queryParams.SearchValue)),
                    _ => flowerQuery
                };
            }

            // Get total count before paging
            var totalRecords = await flowerQuery.CountAsync();

            // Apply paging
            var items = await flowerQuery
                .Skip((queryParams.Page - 1) * queryParams.PageSize)
                .Take(queryParams.PageSize)
                .ToListAsync();

            return new PagedResult<FlowerResponse>
            {
                Items = _mapper.Map<List<FlowerResponse>>(items),
                TotalItems = totalRecords,
                Page = queryParams.Page,
                PageSize = queryParams.PageSize
            };
        }

    }
}
